### ISSUE TITLE
Error when running the application

### ISSUE THREAD

**Issue by ThorvaldAagaard** [indianbridge/bridge-hand-player#1]
In your latest update you have deleted ```bridge-hand-player-min.js```.

I assume the script to create that file is ``` minify.bat```, but that is referring to ```bridge-hand-player.js``` and that file no longer exist.

Changing the name to what I assume is the new file ```jquery-bridge-hand-player```  there is a lot of errors in the output from ```minify.bat```

```
jquery.bridge-hand-player.js:39: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
        class: 'card-table',
        ^

jquery.bridge-hand-player.js:48: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
        class: 'compass',
        ^
```

**Comment by sriram-narasimhan** [comment]
Thanks for point this out. I restored the deleted files.
