### ISSUE TITLE
Using the UI in another solution

### ISSUE THREAD

**Issue by ThorvaldAagaard** [indianbridge/bridge-hand-player#2]
BEN (https://github.com/lorserker/ben) is a bridge engine based on neural networks, and it has a very simple UI based on html and javascript. 

![image](https://github.com/indianbridge/bridge-hand-player/assets/10560652/0af25e65-e633-4986-b2ad-f66359018c06)

![image](https://github.com/indianbridge/bridge-hand-player/assets/10560652/25768671-66fa-494d-8c84-e23db5a04bec)

I would like to improve the UI, but your project has no license information. Can it be used freely?

If yes, would it be simple to isolate the UI to a single page with bidding and play? (using websockets to communicate with the server)

When reviewing the board it looks like this

![image](https://github.com/indianbridge/bridge-hand-player/assets/10560652/cd4a3fe6-54fe-4049-b599-786cd10aaa4c)

That could also use an update.

**Comment by sriram-narasimhan** [comment]
Added a license https://github.com/indianbridge/bridge-hand-player/blob/master/LICENSE

I have not looked at this code for a while so I can't say from top of my head how easy it would be to isolate it to a single page but I have used it in other places so it should be possible.
